version: '3.8'

services:

  challenge-server:
    image: mtrz/challenge-server:2
    restart: always
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres:5432/challenge
    ports:
      - '8080:8080'

  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./challenge-server/dependencies/init-scripts:/docker-entrypoint-initdb.d/
      - postgres-volume:/var/lib/postgresql/data

volumes:
  postgres-volume:
    driver: local